<script>
  import ContentHeader from "./lib/ContentHeader.svelte";
  import ProjectCard from "./lib/ProjectCard.svelte";
  import MiscProjectCard from "./lib/MiscProjectCard.svelte";

  let { contentAnimationDirection } = $props();
</script>

<projects
  class="flex flex-col gap-12 motion-opacity-in-0 pr-16 pb-12 {contentAnimationDirection ===
  'up'
    ? 'animate-small-fade-up'
    : 'animate-small-fade-down'}"
>
  <ContentHeader title="What have I built?" />
  <div
    id="projects-columns"
    class="grid grid-cols-2 lg:grid-cols-3 gap-x-10 group"
  >
    <div id="first-column" class="flex flex-col gap-10">
      <ProjectCard
        title="Transcription app"
        description="Full-stack, containerized web app to transcribe uploaded files into text, using various STT providers, including OpenAI's Whisper, or Gemini's multimodal capabilities. Returns text and a .txt file download. Deployed with Flask, ffmpeg on a VPS."
        githubLink="https://github.com/nocdn/transcription-svelte"
        demoLink="https://whisper.bartoszbak.org"
        techStack={["Svelte", "Flask", "Tailwind"]}
        backgroundColor="white"
        textColor="#511F7D"
        maintained={true}
      />
      <ProjectCard
        title="Society voting platform"
        description="Multi-page web app for a university society election. Complete with a self-hostable backend and Resend API to send out emails with codes."
        githubLink="https://github.com/nocdn/voting"
        demoLink="https://voting.bartoszbak.org"
        techStack={["SvelteKit", "Flask", "Supabase"]}
        backgroundColor="white"
        textColor="#511F7D"
      />
      <ProjectCard
        title="Shared calendar, notes and files"
        description="A full-stack shared calendar, notes and files system for friends and
        family. My first introduction to AWS and Supabase, with a focus on serverless."
        githubLink="https://github.com/nocdn/Non-Exam-Assessment"
        demoLink="https://github.com/nocdn/Non-Exam-Assessment"
        techStack={["Supabase", "JavaScript", "S3", "Lambda", "IAM"]}
        backgroundColor="white"
        textColor="darkBlue"
      />
    </div>
    <div id="second-column" class="flex flex-col gap-10">
      <ProjectCard
        title="Ad segment remover"
        description="RESTful API (with a web interface) to intelligently and automatically remove ad segments from audio and video files."
        githubLink="https://github.com/nocdn/ad-segment-remover"
        demoLink="https://segments.bartoszbak.org"
        techStack={["Svelte", "Flask", "Tailwind"]}
        backgroundColor="white"
        textColor="#A53168"
        maintained={true}
      />
      <ProjectCard
        title="Psychology MCQs"
        description="An app made for my friends to practice for their psychology exams. Progress tracking, updating questions. Questions generated by large language models."
        githubLink="https://github.com/nocdn/mcqs"
        demoLink="https://mcqs.bartoszbak.org"
        techStack={["Svelte", "Supabase", "Lambda"]}
        backgroundColor="white"
        textColor="darkBlue"
      />
      <ProjectCard
        title="Language Learning App"
        description="A small language learning app for school coursework that can be ran locally, and works as a PWA."
        githubLink="https://github.com/nocdn/language-learning"
        demoLink=""
        techStack={["JavaScript"]}
        backgroundColor="white"
        textColor="#511F7D"
      />
    </div>
    <div id="third-column" class="flex flex-col gap-10">
      <ProjectCard
        title="Elo film ranking"
        description="An over-engineered solution to a problem of having a list of things, but
        now knowing the order, ie. favourite films. This app uses an
        elo system to show you all the comparison pairs, and then creates a ranked
        table."
        githubLink="https://github.com/nocdn/films-elo"
        demoLink="https://films-elo.vercel.app/"
        techStack={["TypeScript", "Svelte", "PostgreSQL"]}
        backgroundColor="white"
        textColor="#ca2e00"
        maintained={true}
      />
      <ProjectCard
        title="This website"
        description="How's that for recursion? This is a fairly simple website that I made to introduce myself and showcase some of my skills. It was also a way for me to learn and practice Svelte and Tailwind CSS. It also comes with some fun easter eggs."
        githubLink="https://github.com/nocdn/portfolio-website-svelte"
        demoLink="https://bartoszbak.org"
        techStack={["Svelte", "JavaScript", "Tailwind"]}
        backgroundColor="white"
        textColor="#A53168"
        maintained={true}
      />
    </div>
  </div>
  <p class="text-2xl font-bold font-jetbrains-mono mt-12">
    <span class="opacity-20">##</span> Miscellaneous projects:
  </p>
  <miscProjects class="w-full h-64 p-6 flex gap-10">
    <MiscProjectCard
      rotation={1.5}
      title="Minecraft account finder."
      sourceLink="https://github.com/nocdn/namesniper"
      demoLink="https://github.com/nocdn/namesniper"
      icon="UserSearch"
      colors={[
        "white",
        "white",
        "#9ADB76",
        "#8FD268",
        "#8B624B",
        "#372B1C",
        "#373B39",
        "white",
      ]}
    />
    <MiscProjectCard
      rotation={1.5}
      title="Curseforge pack downloader."
      sourceLink="https://github.com/nocdn/curseforge-modpack-downloader"
      demoLink="https://curseforge-modpack-downloader.vercel.app"
      icon="Anvil"
      colors={[
        "white",
        "white",
        "#F16436",
        "#F16436",
        "#0D0D0D",
        "#0F2B45",
        "#0F2B45",
        "white",
      ]}
    />
    <MiscProjectCard
      rotation={-1.5}
      title="Random topic for revision."
      sourceLink="https://github.com/nocdn/random-revision"
      demoLink="https://random-revision.vercel.app"
      icon="GraduationCap"
      colors={[
        "white",
        "white",
        "#2b2d42",
        "#8d99ae",
        "#edf2f4",
        "#ef476f",
        "#ef233c",
        "white",
      ]}
    />
  </miscProjects>
</projects>
