<script>
  import { onMount } from "svelte";
  import ContentHeader from "./lib/ContentHeader.svelte";
  import MiscProjectCard from "./lib/MiscProjectCard.svelte";
  import ProjectCardAlt from "./lib/ProjectCardAlt.svelte";

  let { contentAnimationDirection, visited, onVisited = () => {} } = $props();

  onMount(() => {
    onVisited(1);
  });
</script>

<projects
  class="flex flex-col gap-12 motion-opacity-in-0 pr-16 pb-12 {contentAnimationDirection ===
  'up'
    ? 'animate-small-fade-up'
    : 'animate-small-fade-down'}"
>
  <ContentHeader title="What have I built?" enabled={!visited} />
  <div class="flex gap-6">
    <column class="flex flex-col gap-6">
      <ProjectCardAlt
        title="Transcription app"
        description="Full-stack, containerized web app to transcribe uploaded files into text, using various STT providers, including OpenAI's Whisper, or Gemini's multimodal capabilities. Returns text and a .txt file download. Deployed with Flask, ffmpeg on a VPS."
        demoLink="https://whisper.bartoszbak.org"
        sourceLink="https://github.com/nocdn/transcriptions"
        stack={["Python", "Flask", "Svelte", "Tailwind CSS"]}
        maintained={true}
      />
      <ProjectCardAlt
        title="Society voting platform"
        description="Multi-page web app for a university society election. Complete with a self-hostable backend and Resend API to send out emails with codes."
        demoLink="https://voting.bartoszbak.org"
        sourceLink="https://github.com/nocdn/voting"
        stack={["Python", "SvelteKit", "Flask", "Supabase"]}
        maintained={false}
      />
      <ProjectCardAlt
        title="This website"
        description="How's that for recursion? This is a fairly simple website that I made to introduce myself and showcase some of my skills. It was also a way for me to learn and practice Svelte and Tailwind CSS. Also packaged with some fun easter eggs."
        demoLink="https://bartoszbak.org"
        sourceLink="https://github.com/nocdn/portfolio"
        stack={["Svelte", "Tailwind CSS", "Vite"]}
        maintained={true}
      />
    </column>
    <column class="flex flex-col gap-6">
      <ProjectCardAlt
        title="Ad segment remover"
        description="RESTful API (with a web interface) to intelligently and automatically remove ad segments from audio and video files."
        demoLink="https://segments.bartoszbak.org"
        sourceLink="https://github.com/nocdn/ad-segment-remover"
        stack={["Python", "Flask", "Svelte", "Tailwind CSS"]}
        maintained={true}
      />
      <ProjectCardAlt
        title="Elo film ranking"
        description="An over-engineered solution to a problem of having a list of things, but now knowing the order, ie. favourite films. This app uses an elo-like system to show you all the comparison pairs, and then creates a ranked table."
        demoLink="https://films-elo.vercel.app/"
        sourceLink="https://github.com/nocdn/films-elo"
        stack={["TypeScript", "Svelte"]}
        maintained={true}
      />
      <ProjectCardAlt
        title="Psychology MCQs"
        description="An app made for my friends to practice for their psychology exams. Progress tracking, updating questions. Questions generated by large language models."
        demoLink="https://mcqs.bartoszbak.org"
        sourceLink="https://github.com/nocdn/mcqs"
        stack={["Svelte", "Python", "Supabase", "Lambda"]}
        maintained={false}
      />
    </column>
    <column class="flex flex-col gap-6">
      <ProjectCardAlt
        title="Temp email generator"
        description="RESTful API to create temporary email addresses with your own domain through cloudflare email routing."
        demoLink=""
        sourceLink="https://github.com/nocdn/cloudflare-temp-mail"
        stack={["Python", "Flask"]}
        maintained={true}
      />
      <ProjectCardAlt
        title="Shared calendar and files"
        description="A full-stack shared calendar, notes and files system for friends and family. My first introduction to AWS and Supabase, with a focus on serverless."
        demoLink=""
        sourceLink="https://github.com/nocdn/Non-Exam-Assessment"
        stack={["Supabase", "JavaScript", "S3", "Lambda", "IAM"]}
        maintained={false}
      />
      <ProjectCardAlt
        title="Language Learning App"
        description="A basic language learning app with a few minigames for school coursework that can be ran locally, and works as a PWA."
        demoLink=""
        sourceLink="https://github.com/nocdn/language-learning"
        stack={["JavaScript"]}
        maintained={false}
      />
    </column>
  </div>
  <p class="text-xl font-bold font-jetbrains-mono mt-12">
    <span class="opacity-20">##</span> Other projects:
  </p>
  <miscProjects class="w-full h-64 p-6 flex gap-10">
    <MiscProjectCard
      rotation={1.5}
      title="Minecraft account finder."
      sourceLink="https://github.com/nocdn/namesniper"
      demoLink="https://github.com/nocdn/namesniper"
      icon="UserSearch"
      colors={[
        "white",
        "white",
        "#9ADB76",
        "#8FD268",
        "#8B624B",
        "#372B1C",
        "#373B39",
        "white",
      ]}
    />
    <MiscProjectCard
      rotation={1.5}
      title="Curseforge pack downloader."
      sourceLink="https://github.com/nocdn/curseforge-modpack-downloader"
      demoLink="https://curseforge-modpack-downloader.vercel.app"
      icon="Anvil"
      colors={[
        "white",
        "white",
        "#F16436",
        "#F16436",
        "#0D0D0D",
        "#0F2B45",
        "#0F2B45",
        "white",
      ]}
    />
    <MiscProjectCard
      rotation={-1.5}
      title="Random topic for revision."
      sourceLink="https://github.com/nocdn/random-revision"
      demoLink="https://random-revision.vercel.app"
      icon="GraduationCap"
      colors={[
        "white",
        "white",
        "#2b2d42",
        "#8d99ae",
        "#edf2f4",
        "#ef476f",
        "#ef233c",
        "white",
      ]}
    />
  </miscProjects>
</projects>
